[program:buncloud-agent]
directory=/www/wwwroot/v2.151376.xyz
command=/www/server/php/81/bin/php artisan queue:work agent --queue=panel_agent --sleep=1 --tries=1 --timeout=0 --memory=128 --max-jobs=100 --max-time=3600
user=www
numprocs=1
autostart=true
autorestart=true
startsecs=2
startretries=10
stopwaitsecs=220
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/www/wwwroot/v2.151376.xyz/storage/logs/agent-worker.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
